<?php
$deshboard_page="dashboard.php";
$log_out_page="account_logout.php";
$admission="admission/registration.php";
$missing_photo="admission/missing_photo.php";
$assign_roll_no="admission/assign_roll_number.php";
$student_search="search/search.php";
$parents_search="parent/parent_list.php";
$tran_add_student="transport/student_allocate_transport.php";
$tran_student_list="transport/student_allocate_list.php";
$tran_route_list="transport/view_route_in_vehicle_details.php";
$tran_vehicle="transport/view_vehicle_details.php";
$tran_setting="transport/transport_system_setting.php";
$tran_add_route="transport/add_route.php";
$trans_add_veh_type="transport/add_vehicle_type.php";
$trans_add_vehicle="transport/add_vehicle.php";
$tran_add_driver="transport/add_driver.php";
$tran_add_route_allot="transport/add_route_and_vehicle.php";
$loader_ajax="ajax_loader_page.php";
?>